name: Run UI Tests from Noon-CMS

on:
  push:
    branches:
      - '*' # Trigger on pushes to any branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout test repository
        uses: actions/checkout@v3

      # Step 2: Clone the Noon-CMS repository
      - name: Clone Noon-CMS repository
        run: git clone https://x-access-token:${{ secrets.NOON_CMS_TOKEN }}@github.com/MSeddikN/Noon-CMS.git

      # Step 3: Set up Java (required for the Noon-CMS project)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 4: Install dependencies (skip tests during this phase)
      - name: Install dependencies
        working-directory: Noon-CMS
        run: mvn install -DskipTests
        
      # Step 5: Install Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 6: Run the specific TestNG suite
      - name: Run tests with debug logs
        working-directory: Noon-CMS
        env:
          CI: true # Ensure CI environment variable is set for headless mode
        run: mvn test -Dtest=HomePageTests#checkChangeCountryFunctionality_NC15

      # Step 7: Upload test reports for debugging
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: Noon-CMS/target/surefire-reports/

      # Step 8: Deploy screenshots to GitHub Pages
      - name: Deploy screenshots to GitHub Pages
        if: always() # Run this step regardless of success or failure
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          cd Noon-CMS
          git fetch
          git checkout -b gh-pages origin/gh-pages || git checkout gh-pages
          mkdir -p screenshots
          mv src/main/resources/screenshots/* screenshots/
          git add screenshots/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Add screenshots from CI run"
            git push origin gh-pages
          else
            echo "No screenshots to upload."
          fi
