name: Run UI Tests from Noon-CMS

on:
#  push:
#    branches:
#      - '*' # Trigger on pushes to any branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository

      - name: Checkout test repository
        uses: actions/checkout@v3

      # Step 2: Clone the Noon-CMS repository
      - name: Clone Noon-CMS repository
       # run: git clone https://x-access-token:${{ secrets.NOON_CMS_TOKEN }}@github.com/MSeddikN/Noon-CMS.git
        run: git clone https://x-access-token:${{ secrets.NOON_CMS_TOKEN }}@github.com/MSeddikN/Noon-API.git


      # Step 3: Set up Java (required for the Noon-CMS project)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 4: Clean the screenshots folder
      - name: Clean screenshots folder
        run: |
          rm -rf Noon-CMS/src/main/resources/screenshots/
          mkdir -p Noon-CMS/src/main/resources/screenshots/
          #chmod -R 777 Noon-CMS/src/main/resources/screenshots/

          
      # Step 5: Install dependencies (skip tests during this phase)
      - name: Install dependencies
        working-directory: Noon-API #Noon-API Noon-CMS
        run: |
            #brew install maven
             mvn install -DskipTests
        
      # Step 6: Install Chrome
      - name: Install Chrome
        run: |
           # brew install --cask google-chrome   
           sudo apt-get update
           sudo apt-get install -y google-chrome-stable 

      # Step 7: Run the specific TestNG suite
      - name: Run tests with debug logs
        working-directory: Noon-API #Noon-API Noon-CMS
        env:
          CI: true # Ensure CI environment variable is set for headless mode
        run:   mvn test -DsuiteXmlFile=src/test/suites/TestSuite.xml      #NoonSimpleTests HomePageTests

      # Step 8: Upload test reports for debugging
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: Noon-CMS/target/surefire-reports/

     # Step 9: Upload screenshots as artifacts
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: Noon-CMS/src/main/resources/screenshots/

      # Step 10: Log artifact link for easy reference
      - name: Log artifact link
        run: |
          echo "Screenshots uploaded! Download them from the [Artifacts section](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})."
